### ISSUE TITLE
Add Stamp node

### ISSUE THREAD

**Issue by Longor1996** [otto-link/Hesiod#174]
A node that accepts an image (from #164 ?) and randomly splats it over/onto the input given a grid/lattice.

- Randomized offset and rotation.
- Lattice of quads/triangles/...?
- Spacing between lattice points?
- Different blending modes?
- Could also be used for heightmaps?

**Comment by otto-link** [comment]
Hi, thanks for the proposition. This could indeed be interesting. The node could take a set of points as an input so that the stamping locations can be defined in various ways, including jittered regular lattices. For naming, I'd rather use "stamping" instead of "splatting" since "splatmap" are generally used when combining texture (could be misleading).

When you say "Could also be used for heightmaps?", what do you have in mind?

This could be something like that:
![image](https://github.com/otto-link/Hesiod/assets/121820229/ed7ff3a2-569c-4779-a5f3-b54f812fdf48)

**Comment by Longor1996** [comment]
> When you say "Could also be used for heightmaps?", what do you have in mind?

Oh, wooops!

`Could also be used for heightmaps?` was meant to be a point under `Different blending modes?`, in the form of `min`/`max`/`add`/`sub` blending modes... seems I accidentally a line there!

---

>  The node could take a set of points as an input so that the stamping locations can be defined in various ways, including jittered regular lattices.

That is *exactly* what I had in mind! :)

---

> For naming, I'd rather use "stamping" instead of "splatting" since "splatmap" are generally used when combining texture (could be misleading).

Ah, right, I thought of calling it stamping, but somehow ended up with splatting... stamping is better.

**Comment by otto-link** [comment]
Hey, I added the `Stamping` node and the others input nodes (lattice, etc...). Let me know if you need a binary to play around (Linux or windows).

![Screenshot_2024-06-14_19-46-48](https://github.com/otto-link/Hesiod/assets/121820229/6be88574-684d-4c72-a2c4-3124aae41bff)
